### ISSUE TITLE
WKYoutubePlayer layout is wrong in landscape mode

### ISSUE THREAD

**Issue by timurbeg** [WayneLin1215/Swift-WKYoutubePlayer#1]
This issue is not consistent. But happens very frequently while repetitive rotation of device. 
On rotation from portrait to landscape, player keeps having portrait frame, occupies 1/4 part of the screen and has alignment of top left.
Frame of player(WKWebView) has correct frame, but several subviews(WKCompositingView) has wrong frames(smaller than player's frame)

In my code I'm using layout constraints for making layout and not using autoResizingMasks:

`view.addSubview(player)`
`player.translatesAutoresizingMaskIntoConstraints = false`
`NSLayoutConstraint.activate([`
`    player.topAnchor.constraint(equalTo: view.topAnchor),`
`    player.bottomAnchor.constraint(equalTo: view.bottomAnchor),`
`    player.leadingAnchor.constraint(equalTo: view.leadingAnchor),`
`    player.widthAnchor.constraint(equalTo: player.heightAnchor, multiplier: 16 / 9)`
`])`

Issue is identified on both Simulator and iPhone devices on iOS 12.x.x-13.x.x.

**Comment by timurbeg** [comment]
RESOLVED: By modifying window.onresize method in YTPlayerView.html template:
`window.onresize = function() {
        setTimeout(function() { player.setSize(window.innerWidth, window.innerHeight) }, 100);
}`

**Comment by WayneRetry** [comment]
Thank you for your solve code, It's bug happend very often when I try device from portrait to land scape, I'll fix on v1.1.0
